### ISSUE TITLE
US-012 - Lister l’ensemble des projets

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#10]
| Wireframe | Fonctionnalités |
|:---:|:---:|
| WI-002 | FE-087 |

## User Story

En tant qu’utilisateur je souhaite accéder à la liste des projets.

## Tasks

- [ ] TB-060 | Créer l'entity, le controller, le repository pour : projet
- [ ] TB-061 | Rédaction des tests
- [ ] TB-062 | Résolution des bugs
