### ISSUE TITLE
US-014 - Modifier un projet

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#12]
| Wireframe | Fonctionnalités |
|:---:|:---:|
|   | FE-015 |

## User Story

En tant qu’utilisateur je souhaite éditer un projet.
Sur la pages “mes projets” je clique sur le bouton d’édition,  un popup s’ouvre sur avec un formulaire qui demande la nouvelle url du projet
Je clique sur le bouton « Valider » afin d’enregistrer les modifications.
Si les données fournies sont valides, le popup se ferme et la liste des projets est mise à jour pour faire apparaître le nouveau projet.

Je suis redirigé vers la liste des projets.

## Tasks

- [ ] TB-071 | Créer une route retournant les deals en fonction du projet sélectionner
- [ ] TB-072 | Rédaction des tests
- [ ] TB-073 | Résolution des bugs
