### ISSUE TITLE
US-016 - Vérifier l’état d’un achat

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#14]
| Wireframe | Fonctionnalités |
|:---:|:---:|
|  | FE-187 |

## User Story

En tant qu’utilisateur je souhaite vérifier l’état d’un achat pour un projet.
j’accède à la page “Netlinking > annonceur > Tous les deals”
La liste des deals du projet sélectionné s’affiche sous forme de tableau les colonnes présentes sont:

- [ ] le libellé
- [ ] support
- [ ] type de produit
- [ ] l’état de l’offre
- [ ] la date de création du deal
- [ ] le prix

je peux alors sélectionner un autre onglet ex: “Netlinking > annonceur >  deals actif”.
Les onglets d’état disponible sont: “Tous les deals, Deals en attente,Deals actifs, archives”.

## Tasks

- [ ] TB-074 | Créer une route retournant les deals en fonction d'un paramètre "état"
- [ ] TB-075 | Rédaction des tests
- [ ] TB-076 | Résolution des bugs
