### ISSUE TITLE
US-017 - Ajouter un compte back office

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#15]
| Wireframe | Fonctionnalités |
|:---:|:---:|
| WI-020 | FE-066 |

## User Story

Sur la page “Administration > Back Office”.
Sur cette page il y a la liste des utilisateurs du back office, en haut à droite de cette liste il y a un bouton “Ajouter un utilisateur”, je clique sur le bouton.
Une popup apparaît avec dedans un formulaire pour ajouter les informations de l’utilisateur, le formulaire demande les informations suivantes :

- Nom
- Prénom
- Email

A chaque fois que j'écris dans un champ, ce champ change de couleur en fonction de si j’ai respecter les regles ou non, la couleur varie entre le rouge et le vert.
En bas du formulaire il y a un bouton “Ajouter l’utilisateur”, qui permet d’enregistrer les modifications.
Je clique sur le bouton “Ajouter l’utilisateur”.

## Exceptions

1. Étant donné que la longueur maximale du champ nom est 50 et ne doit pas contenir de chiffres ou caractères spéciaux , si il ne correspond pas le champ “Nom” passe au statut invalide avec un message pour expliquer que le nom saisi n’est pas valide
2. Étant donné que la longueur maximale du champ prénom est 50 et ne doit pas contenir de chiffres ou caractères spéciaux , si il ne correspond pas le champ “prénom” passe au statut invalide avec un message pour expliquer que le prénom saisi n’est pas valide
3. Étant donné qu’un email doit correspondre au regex suivant : ^[\w\-\.\_+&]+@([\w_-]+\.)+[\w\-_]{2,}$, si elle ne correspond pas le champ “Email” passe au statut invalide avec un message pour expliquer que l’adresse email saisie n’est pas valide.
4. Étant donné qu’une adresse mail doit être utilisée que pour un seul compte à la fois, si l’adresse mail est déjà utilisée un message s’affiche pour expliquer que l’adresse email saisie est déjà utilisée.

## Tasks

- [ ] TB-077 | Enregistrer l'utilisateur
- [ ] TB-078 | Vérifier que tous les champs sont valide
- [ ] TB-079 | Rédaction des tests
- [ ] TB-080 | Résolution des bugs
