### ISSUE TITLE
US-018 - Modifier un compte back office

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#16]
| Wireframe | Fonctionnalités |
|:---:|:---:|
| WI-020 | FE-067  |

## User Story

Sur la page “Administration > Back Office”.
Sur cette page il y a une liste des utilisateurs du back office déjà créé, au bout de chaque ligne il y a une icône (fa-circle-info).
Je clique sur l'icône de la ligne de l’utilisateur que je veux modifier.
Un popup apparaît avec dedans les informations de l’utilisateur dans un formulaire pré-remplie :

- Nom
- Prénom
- Email

A chaque fois que j'écris dans un champ, ce champ change de couleur en fonction de si j’ai respecter les regles ou non, la couleur varie entre le rouge et le vert.
En bas du formulaire il y a deux boutons “Enregistrer” et “Annuler”.
Je clique sur le bouton “Enregistrer” pour modifier les informations de l'utilisateur.

## Exceptions

1. Étant donné que la longueur maximale du champ nom est 50 et ne doit pas contenir de chiffres ou caractères spéciaux , si il ne correspond pas le champ “Nom” passe au statut invalide avec un message pour expliquer que le nom saisi n’est pas valide
2. Étant donné que la longueur maximale du champ prénom est 50 et ne doit pas contenir de chiffres ou caractères spéciaux , si il ne correspond pas le champ “prénom” passe au statut invalide avec un message pour expliquer que le prénom saisi n’est pas valide
3. Étant donné qu’un email doit correspondre au regex suivant : ^[\w\-\.\_+&]+@([\w_-]+\.)+[\w\-_]{2,}$, si elle ne correspond pas le champ “Email” passe au statut invalide avec un message pour expliquer que l’adresse email saisie n’est pas valide.
4. Étant donné qu’une adresse mail doit être utilisée que pour un seul compte à la fois, si l’adresse mail est déjà utilisée un message s’affiche pour expliquer que l’adresse email saisie est déjà utilisée.

## Tasks

- [ ] TB-081 | Vérifier que tous les champs sont valide
- [ ] TB-082 | Update l'utilisateur
- [ ] TB-083 | Rédaction des tests
- [ ] TB-084 | Résolution des bugs
