### ISSUE TITLE
US-019 - Activer/Désactiver un compte back office

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#17]
| Wireframe | Fonctionnalités |
|:---:|:---:|
| WI-020 | FE-068 |

## User Story

Sur la page “Administration > Back Office”.
Sur cette page il y a une liste des utilisateurs du back office déjà créé, au bout de chaque ligne il y a une icône (fa-circle-info) 
Je clique sur l'icône.
Une plateforme apparaît,en haut à droite il y a un switch pour modifier l'état d’activation de l’utilisateur.
Je clique sur le switch pour changer le statut de l’utilisateur.

## Tasks

- [ ] TB-085 | Vérifier que tous les champs sont valide
- [ ] TB-086 | Mettre à jour l'utilisateur
- [ ] TB-087 | Rédaction des tests
- [ ] TB-088 | Résolution des bugs
