### ISSUE TITLE
US-002 - S’inscrire avec Google

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#2]
| Wireframe | Fonctionnalités |
|:---:|:---:|
| WI-001 | FE-002 |

## User Story

En tant qu’internaute j'accède au formulaire d’inscription via les différents liens disponibles.
Le formulaire demande les informations suivantes :
Email
Une case à cocher pour les conditions general d’utilisation

A chaque fois que j'écris dans un champ, ce champ change de couleur en fonction de si j’ai respecter les regles ou non, la couleur varie entre le rouge et le vert.

En bas du formulaire il y a un bouton “S'inscrire”, qui permet de valider son inscription.
Je clique sur le bouton “S'inscrire”.

Si les données saisies sont valides, je suis redirigé vers une deuxième page pour entrer un code, qui vient de m'être envoyé à l’adresse email que j’ai renseigné.

Sur cette page il y a un formulaire

- Mot de passe
- Le mot de passe doit respecter les règles suivantes :
- Au moins 8 caractères
- Au moins une majuscule
- Au moins une minuscule
- Au moins un chiffre

Un bouton qui se situe en dessous des deux champs de mot de passe, permet à l'internaute de créer un mot de passe robuste qui respecte les règles.

Si je clique sur le bouton qui permet de générer un mot de passe robuste, un mot de passe est créé et automatiquement inséré dans les deux champs mot de passe et ajouté au presse papier de l’internaute, un message s’affiche pour prévenir l’internaute que le nouveau mot de passe généré a été copié dans son presse papier.

En dessous du formulaire il y a un bouton pour valider son inscription, je clique dessus.

Je suis alors redirigé vers le tableau de bord de l’application.

## Exceptions

1. Étant donné qu’un email doit correspondre au regex suivant : ^[\w\-\.\_+&]+@([\w_-]+\.)+[\w\-_]{2,}$, si elle ne correspond pas le champ “Email” passe au statut invalide avec un message pour expliquer que l’adresse email saisie n’est pas valide.
2. Étant donné qu’une adresse mail doit être utilisée que pour un seul compte à la fois, si l’adresse mail est déjà utilisée un message s’affiche pour expliquer que l’adresse email saisie est déjà utilisée.
3. Étant donné qu’un mot de passe doit être au moins de 8 caractères et doit contenir au moins une minuscule, une majuscule, et un chiffre. Si il ne correspond pas le champ “Mot de passe” passe au statut invalide, la couleur des règles qui sont pas valide deviennent rouge.

## Tasks

- [ ] Créer l'entity, le controller, le repository pour : user, entreprise
- [ ] Vérifier si l'adresse email est déjà utilisée
- [ ] Vérifier si l'adresse email est du bon format
- [ ] Vérifier que tous les champs sont valide
- [ ] Envoyer le mail de vérification d'adresse email
- [ ] Vérifier si le mot de passe respecter les règles : 8+ caractères, minimum : 1 minuscule, 1 majuscule, 1 chiffre
- [ ] Envoyer le mail de bienvenue
- [ ] Enregistrer le nouvel utilisateur
- [ ] Rédaction des tests
- [ ] Résolution des bugs
