### ISSUE TITLE
US-022 - Modifier un thème

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#20]
| Wireframe | Fonctionnalités |
|:---:|:---:|
| WI-021 | FE-043 |

## User Story

Sur la page “Administration > Netlinkings”.
Je clique sur l’onglet thèmes.
Dans cet onglet il y a une liste des thèmes existant, au bout de chaque ligne il y a une icône (fa-pen).
Je clique sur l’icône de la ligne du thème que je veux modifier.
Une popup apparaît avec dedans un formulaire, pré-remplie avec les informations du thème, qui demande les informations suivantes :

- Nom

A chaque fois que j'écris dans un champ, ce champ change de couleur en fonction de si j’ai respecter les regles ou non, la couleur varie entre le rouge et le vert.
En bas du formulaire il y a deux boutons “Enregistrer” et “Annuler”.
Je clique sur le bouton “Enregistrer” pour modifier les informations du thème.

## Tasks

- [ ] TB-098 | Vérifier que tous les champs sont valide
- [ ] TB-099 | Enregistrer le thème
- [ ] TB-100 | Rédaction des tests
- [ ] TB-101 | Résolution des bugs
