### ISSUE TITLE
US-023 - Ajouter des crédits

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#21]
| Wireframe | Fonctionnalités |
|:---:|:---:|
|  | FE-028 |

## User Story

En tant qu’utilisateur je souhaite ajouter des crédits
Sur la page “Porte-monnaie” je clique sur le bouton “Ajouter des crédits”, un pop-up s’ouvre avec un formulaire contenant le montant que je souhaite ajouter.
je clique sur le bouton “Ajouter” .
Un popup s’ouvre et affiche les informations nécessaires au virement

## Tasks

- [ ] TB-102 | Enregistrer l'ajout de crédit ( libelle du virement )
- [ ] TB-103 | Rédaction des tests
- [ ] TB-104 | Résolution des bugs
