### ISSUE TITLE
US-024 - Supprimer un thème

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#22]
| Wireframe | Fonctionnalités |
|:---:|:---:|
| WI-021 | FE-044 |

## User Story

Sur la page “Administration > Netlinkings”.
Je clique sur l’onglet thèmes.
Dans cet onglet il y a une liste des thèmes existant, au bout de chaque ligne il y a une icône (fa-trash).
Je clique sur l’icône de la ligne du thème que je veux supprimer.
Une popup apparaît pour demander si l’administrateur est sûr de vouloir supprimer le thème, en dessous il y a deux bouton “Annuler” et “Supprimer définitivement”
Je clique sur le bouton “Supprimer définitivement” pour supprimer le thème.

## Exceptions 

1. Le thème ne peut être supprimé que s' il n’existe pas de support relié à ce thème, sinon l’administrateur reçoit un message lui expliquant qu’il est impossible de supprimer le thème car au moins un support y est relié.

## Tasks

- [ ] TB-105 | Vérifier que le thème n'est pas utilisé
- [ ] TB-106 | Supprimer le thème
- [ ] TB-107 | Rédaction des tests
- [ ] TB-108 | Résolution des bugs
