### ISSUE TITLE
US-025 - Ajouter un type de produit

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#23]
| Wireframe | Fonctionnalités |
|:---:|:---:|
| WI-021 | FE-045 |

## User Story

Sur la page “Administration > Netlinkings”.
Je clique sur l’onglet types de produit.
Dans cet onglet il y a un bouton “Ajouter”.
Je clique sur ce bouton.
Une popup apparaît avec dedans un formulaire qui demande les informations suivantes :

- Nom

A chaque fois que j'écris dans un champ, ce champ change de couleur en fonction de si j’ai respecter les regles ou non, la couleur varie entre le rouge et le vert.
En bas du formulaire il y a un bouton “Ajouter le type de produit”, qui permet d’enregistrer le thème.
Je clique sur le bouton “Ajouter le type de produit”.

## Tasks

- [ ] TB-109 | Créer l'entity, le controller, le repository pour : type de produit
- [ ] TB-110 | Vérifier que tous les champs sont valide
- [ ] TB-111 | Enregistrer le type de produit
- [ ] TB-112 | Rédaction des tests
- [ ] TB-113 | Résolution des bugs
