### ISSUE TITLE
US-026 - Modifier un type de produit

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#24]
| Wireframe | Fonctionnalités |
|:---:|:---:|
| WI-021 | FE-046 |

## User Story

Sur la page “Administration > Netlinkings”.
Je clique sur l’onglet thèmes.
Dans cet onglet il y a une liste des types de produit existant, au bout de chaque ligne il y a une icône (fa-pen).
Je clique sur l’icône de la ligne du type de produit que je veux modifier.
Une popup apparaît avec dedans un formulaire, pré-remplie avec les informations du type de produit, qui demande les informations suivantes :

- Nom

A chaque fois que j'écris dans un champ, ce champ change de couleur en fonction de si j’ai respecter les regles ou non, la couleur varie entre le rouge et le vert.
En bas du formulaire il y a deux boutons “Enregistrer” et “Annuler”.
Je clique sur le bouton “Enregistrer” pour modifier les informations du type de produit.

## Tasks

- [ ] TB-114 | Vérifier que tous les champs sont valide
- [ ] TB-115 | Enregistrer le type de produit
- [ ] TB-116 | Rédaction des tests
- [ ] TB-117 | Résolution des bugs
