### ISSUE TITLE
US-027 - Supprimer un type de produit

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#25]
| Wireframe | Fonctionnalités |
|:---:|:---:|
|  | FE-080,FE-081 |

## User Story

Sur la page “Administration > Netlinkings”.
Je clique sur l’onglet thèmes.
Dans cet onglet il y a une liste des types de produit existant, au bout de chaque ligne il y a une icône (fa-trash).
Je clique sur l’icône de la ligne du type de produit que je veux supprimer.
Une popup apparaît pour demander si l’administrateur est sûr de vouloir supprimer le type de produit, en dessous il y a deux bouton “Annuler” et “Supprimer définitivement”
Je clique sur le bouton “Supprimer définitivement” pour supprimer le type de produit.

## Exceptions

1. Le type de produit ne peut être supprimé que s' il n’existe pas de produit relié à ce type, sinon l’administrateur reçoit un message lui expliquant qu’il est impossible de supprimer le type car au moins un produit y est relié.

## Tasks

- [ ] TB-118 | Vérifier que le type de produit n'est pas utilisé
- [ ] TB-119 | Supprimer le type de produit
- [ ] TB-120 | Rédaction des tests
- [ ] TB-121 | Résolution des bugs
