### ISSUE TITLE
US-028 - Ajouter un type de support

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#26]
| Wireframe | Fonctionnalités |
|:---:|:---:|
| WI-021| FE-048 |

## User Story

Sur la page “Administration > Netlinkings”.
Je clique sur l’onglet types de support.
Dans cet onglet il y a un bouton “Ajouter”.
Je clique sur ce bouton.
Une popup apparaît avec dedans un formulaire qui demande les informations suivantes :

- Nom

A chaque fois que j'écris dans un champ, ce champ change de couleur en fonction de si j’ai respecter les regles ou non, la couleur varie entre le rouge et le vert.
En bas du formulaire il y a un bouton “Ajouter le type de support”, qui permet d’enregistrer le thème.
Je clique sur le bouton “Ajouter le type de support”.

## Tasks

- [ ] TB-122 | Créer l'entity, le controller, le repository pour : type de support
- [ ] TB-123 | Vérifier que tous les champs sont valide
- [ ] TB-124 | Enregistrer le type de support
- [ ] TB-125 | Rédaction des tests
- [ ] TB-126 | Résolution des bugs
