### ISSUE TITLE
US-029 - Modifier un type de support

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#27]
| Wireframe | Fonctionnalités |
|:---:|:---:|
| WI-021 | FE-049 |

## User Story

Sur la page “Administration > Netlinkings”.
Je clique sur l’onglet thèmes.
Dans cet onglet il y a une liste des types de support existant, au bout de chaque ligne il y a une icône (fa-pen).
Je clique sur l’icône de la ligne du type de support que je veux modifier.
Une popup apparaît avec dedans un formulaire, pré-remplie avec les informations du type de support, qui demande les informations suivantes :

- Nom

A chaque fois que j'écris dans un champ, ce champ change de couleur en fonction de si j’ai respecter les regles ou non, la couleur varie entre le rouge et le vert.
En bas du formulaire il y a deux boutons “Enregistrer” et “Annuler”.
Je clique sur le bouton “Enregistrer” pour modifier les informations du type de support.

## Tasks

- [ ] TB-127 | Vérifier que tous les champs sont valide
- [ ] TB-128 | Enregistrer le type de support
- [ ] TB-129 | Rédaction des tests
- [ ] TB-130 | Résolution des bugs
- [ ]
