### ISSUE TITLE
US-030 - Supprimer un type de support

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#28]
| Wireframe | Fonctionnalités |
|:---:|:---:|
| WI-021 | FE-050 |

## User Story

Sur la page “Administration > Netlinkings”.
Je clique sur l’onglet thèmes.
Dans cet onglet il y a une liste des types de support existant, au bout de chaque ligne il y a une icône (fa-trash).
Je clique sur l’icône de la ligne du type de support que je veux supprimer.
Une popup apparaît pour demander si l’administrateur est sûr de vouloir supprimer le type de support, en dessous il y a deux bouton “Annuler” et “Supprimer définitivement”
Je clique sur le bouton “Supprimer définitivement” pour supprimer le type de support.

## Exceptions

1. Le type de support ne peut être supprimé que s' il n’existe pas de support relié à ce type, sinon l’administrateur reçoit un message lui expliquant qu’il est impossible de supprimer le type car au moins un support y est relié.

## Tasks

- [ ] TB-131 | Vérifier que le type de support n'est pas utilisé
- [ ] TB-132 | Supprimer le type de support
- [ ] TB-133 | Rédaction des tests
- [ ] TB-134 | Résolution des bugs
