### ISSUE TITLE
US-031 - Rechercher un support

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#29]
| Wireframe | Fonctionnalités |
|:---:|:---:|
| WI-011,WI-012 | FE-032 |

## User Story

Sur la page “Netlinkings > Annonceur > Recherche”.
Sur cette page il y un formulaire, le formulaire demande les informations suivantes : 

- Url
- TF & CF (min et max)
- Thèmes
- Prix (min et max)

En bas du formulaire il y a un lien “Recherche avancée”.
cela rajoute les filtres suivant

- nb de mots clés semrush
- domain rating
- nombre de backlinks
- nombre de visite estimé 
- En dessous de ce formulaire il y a un bouton “Rechercher”, je clique sur le bouton pour faire afficher les supports qui correspondent aux critères de recherche.
- Un tableau apparaît avec les résultats de la recherche.
- Dans le tableau les colonnes présentes sont:
- l'éditeur
- les thématiques
- le prix ( le moins cher ? )
- trust flow
- Citation flow
- nombre de visite estimé 
- nb de mots clés semrush  ( si filtré )
- domain rating   ( si filtré )
- nombre de backlinks ( si filtré )
- 

## Tasks

- [ ] TB-135 | Créer la route retournant la liste des supports en fonction des paramètres
- [ ] TB-136 | vérifier que les champs sont valide
- [ ] TB-137 | Rédaction des tests
- [ ] TB-138 | Résolution des bugs
