### ISSUE TITLE
US-003 - Se connecter

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#3]
| Wireframe | Fonctionnalités |
|:---:|:---:|
| WI-005 | FE-004 |

## User Story

En tant qu’internaute j'accède au formulaire de connexion via les différents liens disponibles.

Sur cette page, il y a le formulaire de connexion
Le formulaire demande les informations suivantes :
Email
Mot de passe

Je clique sur le bouton “Connexion” en bas du formulaire afin de me connecter.

Si les données saisies sont valides, je suis redirigé vers le tableau de bord de l’application.

## Exceptions

1. Etant donné que le mot de passe et l’adresse mail de l’utilisateur doivent être valides et correspondre au même compte utilisateur, si ce n’est pas le cas on affiche un message d’erreur pour prévenir l’internaute que le mot de passe ou l’adresse email ne sont pas bons.

## Tasks

- [ ] Vérifier si l'adresse email existe
- [ ] Vérifier que le compte associé existe et n'est pas désactivé
- [ ] Enregistrer la session de l'utilisateur
- [ ] Rédaction des tests
- [ ] Résolution des bugs
