### ISSUE TITLE
US-032 - Ajouter un support

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#30]
| Wireframe | Fonctionnalités |
|:---:|:---:|
|   | FE-026 |

## User Story

Sur la page “Netlinking > Editeur > mes sites”.

Je clique sur le bouton “Ajouter un site”.
Je suis redirigé vers la page de procédure d’ajout de site.

- Etape 1:
   - Url du site 
- Etape 2: 
   - Thématiques du site
   - Présentation du site
   - Pays cible
   - Langue(s)
- Etape 3:
   - Thématiques refusées du site
   - Délai de rédaction
   - optionnellement, remarques dans un textarea prévu à cet effet
- Etape 4 (ajout de produit):
   - prix one-shot
   - nombre de mots.
   - qui rédige entre l’annonceur ou l'éditeur.
   - délai d’acceptation
   - délai de rédaction
   - mention “Article sponsorisé”

Je clique sur “Ajouter”

## Tasks

- [ ] TB-139 | Enregistrer un produit
- [ ] TB-140 | Enregistrer support
- [ ] TB-141 | Verifier que les champs sont valide
- [ ] TB-142 | Rédaction des tests
- [ ] TB-143 | Résolution des bugs
