### ISSUE TITLE
US-033 - Ajouter un produit

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#31]
| Wireframe | Fonctionnalités |
|:---:|:---:|
|   | FE-039 |

## User Story

En tant qu’utilisateur je souhaite ajouter un produit, j’accède à la page “Netlinking > Editeur > mes sites”.
La liste de mes sites s’affiche. Un bouton pour chaque site me permet d'éditer les produits disponibles.
je clique sur ce bouton.
La liste des produits actuellement disponibles pour le site sélectionné s’affiche.
un bouton “ajouter un produit” me redirige vers la page d’ajout de produit.
Un formulaire est présent.
je renseigne

- prix one-shot
- nombre de mots.
- qui rédige entre l’annonceur ou l'éditeur.
   - délai d’acceptation
   - délai de rédaction
   - mention “Article sponsorisé”

je clique sur le bouton “enregistrer” 
Un message m’indique que le produit a bien été ajouté.

## Tasks

- [ ] TB-144 | Verifier que les champs sont valide
- [ ] TB-145 | Enregistrer le support
- [ ] TB-146 | Rédaction des tests
- [ ] TB-147 | Résolution des bugs
