### ISSUE TITLE
US-034 - Visualiser les informations d’un support

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#32]
| Wireframe | Fonctionnalités |
|:---:|:---:|
|   | FE-034 |

## User Story

Sur la page “Netlinkings > Annonceur > Recherche”.
Après avoir recherché un support, je clique sur la ligne d’un support pour visualiser les informations.
Une plateforme s’ouvre avec les informations suivante : 

- Nom
- favicon
- certificat SSL
- date de création du nom de domaine
- date de première utilisation du nom de domaine,
- les KPIs
- produits proposer
- thèmes
- avis
- screenshots de chaque année depuis la date de première utilisation du nom de domaine

## Tasks

- [ ] TB-148 | Créer une route renvoyant le détail des informations pour un support
- [ ] TB-149 | Rédaction des tests
- [ ] TB-150 | Résolution des bugs
