### ISSUE TITLE
US-035 - Vérifier l'état d’un lien

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#33]
| Wireframe | Fonctionnalités |
|:---:|:---:|
|   | FE-036 |

## User Story

Sur la page “Netlinkings > Annonceur > Mes deals”.
Il y a la liste des achats que j’ai effectué, je clique sur une ligne d’un deal pour avoir le détail de ses informations.
Je suis redirigé vers la page “Détails d’un deal”, sur cette page il y a les informations du deal (date de création, état, brief, …).
Si l’article a déjà été publié, en bas de la page il y a des cases qui représente le statut du lien sur les 30 derniers jours glissant (Voir la gestion des publications sur la station)

## Tasks

- [ ] TB-151 | Créer une tache CRON vérifiant le statut des liens
- [ ] TB-152 | Renvoyer les données de statut dans la route de détail des informations pour un support
- [ ] TB-153 | Rédaction des tests
- [ ] TB-154 | Résolution des bugs
