### ISSUE TITLE
US-036 - Acheter un article sponsorisé

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#34]
| Wireframe | Fonctionnalités |
|:---:|:---:|
|  | FE-034 |

## User Story

Sur la page “Netlinkings > Annonceur > Recherche”.
Après avoir fait la recherche d’un support, je clique sur la ligne du support.
Une plateforme apparaît avec les informations du support, en bas de cette plateforme il y a les “produits” que propose le support. Je clique sur le bouton “Faire une offre”.
Je suis rediriger vers la page “Commande”, Sur cette page il y a un formulaire qui demande les informations suivantes :

- Qui doit rédiger l’article ?
- Projet associe (pré-remplie)
- Délai accordé à l'éditeur pour accepter l’offre
- Délai accordé à l'éditeur pour rédiger l’article (Si rédigé par l’éditeur)
- Prix
- Nombre de mot (Si rediger par l’éditeur)
- Brief
- Date d’envoie de l’offre (Maintenant, Programmé, en brouillon)

En bas du formulaire il y a un bouton qui permet d’enregistrer le formulaire.
Je clique sur ce bouton, je suis redirigé vers la page “Netlinkings > Annonceur > Tous les deals et offres”.

## Tasks

- [ ] TB-155 | Vérifier que les champs sont valide
- [ ] TB-156 | Enregistrer la demande
- [ ] TB-157 | Envoyer un mail pour prévenir de la commande
- [ ] TB-158 | Rédaction des tests
- [ ] TB-159 | Résolution des bugs
