### ISSUE TITLE
US-037 - Envoyer des messages entre le vendeur et l’acheteur

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#35]
| Wireframe | Fonctionnalités |
|:---:|:---:|
|   | FE-089 |

## User Story

En tant qu’utilisateur je souhaite envoyer des messages entre vendeur et acheteur, j’accède au détails d’un deal.
Si le deal est en proposition,en négociation, accepté ou relecture. J’ai la possibilité d’échanger des messages avec la personne avec laquelle le deal est fait.
Les messages sont affichés à la manière d’un chat.
Un textarea permet de renseigner le message à envoyer, j’ai également la possibilité d'ajouter une ou plusieurs pièces jointes. Un bouton “Envoyer”  permet d’envoyer le message

## Exceptions

- Le message est trop long
- Les pièces jointe est trop lourde

## Tasks

- [ ] TB-160 | Vérifier que les champs sont valide
- [ ] TB-161 | Envoyer un mail pour prévenir de l'évolution de la situation
- [ ] TB-162 | Enregistrer le message
- [ ] TB-163 | Rédaction des tests
- [ ] TB-164 | Résolution des bugs
