### ISSUE TITLE
US-038 - Annuler un deal

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#36]
| Wireframe | Fonctionnalités |
|:---:|:---:|
|   | FE-037 |

## User Story

En tant qu’utilisateur je souhaite annuler un deal, j’accède au détails d’un deal.
Si le deal est en brouillon,programmé, en proposition ou en négociation. J’ai la possibilité d’annuler le deal.
un bouton “annuler” affiche un popup et demande une confirmation “Voulez-vous réellement annuler le deal ?”. 
Le popup contient deux boutons, “Oui”,”Non”. je clique sur Oui. 
Un message s’affiche me confirmant la suppression du deal.

## Tasks

- [ ] TB-165 | Modifier l'état du deal
- [ ] TB-166 | Rédaction des tests
- [ ] TB-167 | Résolution des bugs
