### ISSUE TITLE
US-039 - Négocier un prix

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#37]
| Wireframe | Fonctionnalités |
|:---:|:---:|
|  | FE-035 |

## User Story

En tant qu’utilisateur je souhaite négocier un prix, j’accède au détails d’un deal.
Si le deal est en proposition ou en négociation et que le produit permet la négociation. J’ai la possibilité d’échanger sur le prix du produit.
Dans le chat permettant l’échange de message entre vendeur et acheteur. 
En tant qu’acheteur un bouton permet de faire une offre, je renseigne le prix et le nombre de mots, un bouton “Envoyer”  permet d’envoyer l’offre.
En tant que vendeur, l’offre s’affiche dans le chat, avec trois boutons “accepter” ou “refuser” ou contre-offre.
Au bout de 5 offres refusées, le deal est annulé.

## Tasks

- [ ] TB-168 | Vérifier que les champs sont valide
- [ ] TB-169 | Enregistrer le message et le nouveaux prix
- [ ] TB-170 | Envoyer un mail pour prévenir de l'évolution de la situation
- [ ] TB-171 | Rédaction des tests
- [ ] TB-172 | Résolution des bugs
