### ISSUE TITLE
US-040 - Archiver un produit

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#38]
| Wireframe | Fonctionnalités |
|:---:|:---:|
|   | FE-041 |

## User Story

Sur la page “Netlinkings > Editeur > Mes sites”.
Je clique sur la ligne du site qui a le produit que je veux archiver, je suis redirigé vers une page de détails du site.
En bas de cette page il y a les produits du site en format tableau, je clique sur l'icône archiver.
Une popup apparaît pour demander si l’utilisateur est sûr de vouloir supprimer le produit, en dessous il y a deux bouton “Annuler” et “Supprimer définitivement”
Je clique sur le bouton “Supprimer définitivement” pour supprimer le produit.

## Tasks

- [ ] TB-173 | Enregistrer le produit
- [ ] TB-174 | Rédaction des tests
- [ ] TB-175 | Résolution des bugs
