### ISSUE TITLE
US-041 - Modifier un produit

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#39]
| Wireframe | Fonctionnalités |
|:---:|:---:|
|   | FE-040 |

## User Story

En tant qu’utilisateur je souhaite ajouter un produit, j’accède à la page “Netlinking > Editeur > mes sites”.
La liste de mes sites s’affiche. Un bouton pour chaque site me permet d'éditer les produits disponibles.
je clique sur ce bouton.
La liste des produits actuellement disponibles pour le site sélectionné s’affiche.
un bouton “éditer” est présent pour chaque produit. Je clique sur le bouton, je suis redirigé  vers la page d’édition de produit.
Un formulaire pré-rempli est présent.
je peux renseigner le prix one-shot ou le prix au mots et le nombre de mots minimum.
Je peux sélectionner qui rédige entre l’annonceur ou l'éditeur.
je peux renseigner le délai.
je clique sur le bouton “enregistrer” 
Un message m’indique que le produit a bien été modifié.

## Tasks

- [ ] TB-176 | Enregistrer le produit
- [ ] TB-177 | Vérifier que les champs sont valides
- [ ] TB-178 | Rédaction des tests
- [ ] TB-179 | Résolution des bugs
- [ ]
