### ISSUE TITLE
US-004 - Se connecter avec Google

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#4]
| Wireframe | Fonctionnalités |
|:---:|:---:|
| WI-005 | FE-005 |

## User Story

En tant qu’internaute j'accède au formulaire de connexion via les différents liens disponibles.

Sur cette page, il y a un bouton pour se connecter avec son compte Google au-dessus du formulaire de connexion.

Je clique sur le bouton “Connexion avec Google” afin de me connecter.

Après avoir sélectionné le compte Google utilisé pour me connecter, si le compte Google correspond à un compte utilisateur je suis redirigé vers le tableau de bord de l’application.

## Exceptions

1. Etant donné que le processus de connexion de Google doit être complété avec succès, si ce n’est pas le cas l’internaute est redirigé vers la page de connexion avec un message pour le prévenir que la connexion avec Google n’a pas fonctionner.
2. Etant donné que le compte Google doit correspondre à un compte utilisateur sur l’application, si ce n’est pas le cas ’l'internaute est redirigé vers la page de connexion avec un message pour le prévenir que la connexion avec Google n’a pas fonctionner car il n’y a pas de compte sur l’application pour ce compte Google.

## Tasks

- [ ] Vérifier que le token du compte Google est correct
- [ ] Vérifier que le compte associé existe et n'est pas désactivé
- [ ] Rédaction des tests
- [ ] Résolution des bugs
