### ISSUE TITLE
US-042 - Inscrire un support

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#40]
| Wireframe | Fonctionnalités |
|:---:|:---:|
|   | FE-072 |

## User Story

Sur la page “Administration > Netlinking”.

Je clique sur le bouton “Inscrire un support”.
Je suis redirigé vers la page de procédure d'inscription de support.

- Etape 1:
   -  je renseigne l’email du client
- Etape2:
   - je renseigne l’url du site 
- Etape 3: 
   - je renseigne les thématiques du site
   - je renseigne la présentation du site
- Etape 4:
   - je renseigne les thématiques refusées du site
   - je renseigne si la mention “Article sponsorisé” est présente
   - je renseigne le délai de rédaction
   - optionnellement,je renseigne des remarques dans un textarea prévu à cet effet
- Etape 5:
   - je renseigne le nombre de mots par article
   - je renseigne le montant qui sera chargé aux annonceurs

Je clique sur “Ajouter”

## Tasks

- [ ] TB-180 | Enregistrer un produit
- [ ] TB-181 | Enregistrer support
- [ ] TB-182 | Verifier que les champs sont valide
- [ ] TB-183 | Rédaction des tests
- [ ] TB-184 | Résolution des bugs
