### ISSUE TITLE
TA-002 - Mise en place du projet back 	 	 	 	

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#41]
## Tasks

- [ ] TB-001 | Créer le projet spring boot
- [ ] TB-002 | Sécuriser L'API
- [ ] TB-003 | Créer le conteneur
- [ ] TB-004 | Créer le git
- [ ] TB-005 | Ajouter le CI/CD
