### ISSUE TITLE
US-005 - Réinitialisation du mot de passe lors de la connexion

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#5]
| Wireframe | Fonctionnalités |
|:---:|:---:|
| WI-005, WI-006 | FE-006, FE-091 |

## User Story

En tant qu’internaute j'accède au formulaire de connexion via les différents liens disponibles.

Sur cette page, il y a un lien cliquable au-dessous du formulaire de connexion pour réinitialiser mon mot de passe.

Je clique sur le lien “Mot de passe oublié ?”.
Je suis redirigé vers la page de d’envoie de mail pour la réinitialisation de mot de passe.
Sur cette page il y a le formulaire de réinitialisation de mot de passe.
Le formulaire demande l’information suivante :
 - Email

En dessous du formulaire il y a un bouton pour envoyer la demande de réinitialisation.
Je clique sur le bouton “Réinitialiser mon mot de passe”.
Si l’email saisi est valide, un message s’affiche avec marquer “Un email vient de vous être envoyé à l’adresse saisie, afin de réinitialiser votre mot de passe suivez les instructions de l’email”, un lien cliquable s’affiche pour propose de renvoyer le mail à l'adresse email saisie.

Si je clique sur ce lien, un mail avec les instructions pour réinitialiser mon mot de passe me sera renvoyé.

Dans le mail que je viens de recevoir il y a un lien pour réinitialiser mon mot de passe.
Je clique sur ce lien.
Mon navigateur par défaut s’ouvre sur la page de réinitialisation de mot de passe.
Sur cette page il y a un formulaire.
Le formulaire demande les informations suivantes :
 - Mot de passe
    - Le mot de passe doit respecter les règles suivantes :
    - Au moins 8 caractères
    - Au moins une majuscule
    - Au moins une minuscule
    - Au moins un chiffre

Un bouton qui se situe en dessous des deux champs de mot de passe, permet à l'internaute de créer un mot de passe robuste qui respecte les règles.

Si je clique sur le bouton qui permet de générer un mot de passe robuste, un mot de passe est créé et automatiquement inséré dans les deux champs mot de passe et ajouté au presse papier de l’internaute, un message s’affiche pour prévenir l’internaute que le nouveau mot de passe généré a été copié dans son presse papier.

En bas du formulaire il y a un bouton “Modifier le mot de passe”, qui permet de valider la modification du mot de passe.
Je clique sur le bouton “Modifier le mot de passe”.

Si le mot de passe saisi est valide un message s’affiche avec marquer “Le mot de passe a bien été réinitialisé vous pouvez maintenant vous connecter avec votre adresse mail et votre nouveaux mot de passe”.

Je suis redirigé vers la page de connexion.

## Exceptions

1. Étant donné que l’email saisi doit correspondre à un compte utilisateur, si ce n’est pas le cas un message s’affiche pour le prévenir que l’adresse email saisie n’est pas reliée à un compte dans l’application.
2. Étant donné qu’un mot de passe doit être au moins de 8 caractères et doit contenir au moins une minuscule, une majuscule, et un chiffre. Si il ne correspond pas le champ “Mot de passe” passe au statut invalide, la couleur des règles qui sont pas valide deviennent rouge.
3. Étant donné que le mot de passe doit être ressaisie dans le champ “Confirmation mot de passe”, si les deux chaînes de caractères ne sont pas identiques, le champ “Confirmation mot de passe” passe au statut invalide.

## Tasks

- [ ] TB-035 | Créer l'entity, le controller, le repository change_password
- [ ] TB-036 | Vérifier si l'adresse email existe
- [ ] TB-037 | Vérifier que le compte associé existe et n'est pas désactivé
- [ ] TB-038 | Enregistrer la demande de mot de passe
- [ ] TB-039 | Envoyer le mail de modification de mot de passe
- [ ] TB-040 | Vérifier que tous les champs sont valide
- [ ] TB-041 | Modifier le mot de passe de l'utilisateur
- [ ] TB-042 | Rédaction des tests
- [ ] TB-043 | Résolution des bugs
