### ISSUE TITLE
US-008 - Ajouter une entreprise

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#7]
| Wireframe | Fonctionnalités |
|:---:|:---:|
| WI-005 | FE-007 |

## User Story

Sur la page “Paramètres du compte”.
Sur cette page il y un formulaire pour ajouter les informations d’une entreprise, le formulaire demande les informations suivantes :

- Type (Société, EI, Association)
- Nom
- Numéro de SIRET
- Numéro de TVA
- Adresse

A chaque fois que j'écris dans un champ, ce champ change de couleur en fonction de si j’ai respecter les regles ou non, la couleur varie entre le rouge et le vert.
En bas du formulaire il y a un bouton “Enregistrer”, qui permet d’enregistrer les modifications.
Je clique sur le bouton “Enregistrer”.

## Tasks

- [ ] TB-048 | Vérifier que tous les champs sont valide
- [ ] TB-049 | Modifier les informations personnelles de l'utilisateur
- [ ] TB-050 | Rédation des tests
- [ ] TB-051 | Résolution des bugs
