### ISSUE TITLE
US-009 - Ajouter un compte utilisateur affilié à une entreprise

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#8]
| Wireframe | Fonctionnalités |
|:---:|:---:|
| WI-005 | FE-009 |

## User Story

Sur la page “Paramètres du compte”.
Sur cette page il y a une liste des utilisateurs déjà créé dans mon entreprise, en haut à droite de cette liste il y a un bouton “Ajouter un utilisateur”.
Je clique sur ce bouton.
Une popup apparaît avec dedans un formulaire pour ajouter les informations de l’utilisateur, le formulaire demande les informations suivantes :

- Email(s)

A chaque fois que j'écris dans un champ, ce champ change de couleur en fonction de si j’ai respecter les regles ou non, la couleur varie entre le rouge et le vert.
En bas du formulaire il y a un bouton “Envoyer une invitation”, qui permet d’envoyer une invitation à rejoindre l’entreprise.
Je clique sur le bouton “Envoyer une invitation”.
Lorsque l’utilisateur invité reçoit le mail d’invitation. Un bouton est présent dans l’email, il permet d’accepter l'invitation.
Pour accepter l’invitation il faut être connecter et avoir ses informations personnelles renseignées.
Si ce n’est pas le cas, redirection vers login ou création de compte et ensuite obligation de renseigner ses informations personnelles.

## Exceptions

1. Étant donné qu’un email doit correspondre au regex suivant : ^[\w\-\.\_+&]+@([\w_-]+\.)+[\w\-_]{2,}$, si elle ne correspond pas le champ “Email” passe au statut invalide avec un message pour expliquer que l’adresse email saisie n’est pas valide.

## Tasks

- [ ] TB-052 | Vérifier que tous les champs sont valide
- [ ] TB-053 | Envoyer le(s) mail(s) d'invitation
- [ ] TB-054 | Rédaction des tests
- [ ] TB-055 | Résolution des bugs
