### ISSUE TITLE
US-011 - Modifier mon mot de passe

### ISSUE THREAD

**Issue by quentin-gorak** [MethodzLabs/seo-jungle-kotlin#9]
| Wireframe | Fonctionnalités |
|:---:|:---:|
|   | FE-175 |

## User Story

Sur la page “Paramètres du compte”.
Je clique sur le bouton “Modifier mon mot de passe”
Une popup apparaît avec un formulaire demandant les informations suivantes :

- Ancien mot de passe
    - L’ancien mot de passe doit correspondre au mot de passe actuel du compte
- Nouveau mot de passe
- Confirmation nouveau mot de passe
- Le nouveau mot de passe doit respecter les règles suivantes :
   - Au moins 8 caractères
   - Au moins une majuscule
   - Au moins une minuscule
   - Au moins un chiffre

En bas du formulaire il y a un bouton “Modifier”, qui permet de valider la modification du mot de passe.
Je clique sur le bouton “Modifier”.
Une popup apparaît pour demander si l’utilisateur est sûr de vouloir modifier son mot de passe, en dessous il y a deux bouton “Annuler” et “Enregistrer”
Je clique sur le bouton “Enregistrer”.

## Exceptions

1. Si l'ancien mot de passe ne correspond pas au mot de passe réel, le champ “ancien mot de passe” passe au statut invalide, la couleur des règles qui sont pas valide deviennent rouge.
2. Étant donné que le nouveau mot de passe doit être d’au moins de 8 caractères et doit contenir au moins une minuscule, une majuscule, et un chiffre. Si il ne correspond pas le champ “Nouveau mot de passe” passe au statut invalide, la couleur des règles qui sont pas valide deviennent rouge.
3. Étant donné que le mot de passe doit être ressaisie dans le champ “Confirmation nouveau mot de passe”, si les deux chaînes de caractères ne sont pas identiques, le champ “Confirmation mot de passe” passe au statut invalide.

## Tasks

- [ ] Back | TB-052 | Vérifier que tous les champs sont valide
- [ ] Back | TB-053 | Envoyer le(s) mail(s) d'invitation
- [ ] Back | TB-054 | Rédaction des tests
- [ ] Back | TB-055 | Résolution des bugs
